module.exports = {
  ammo: Number,
  armor: Number,
  armor_regen: Number,
  battlesuit: Number,
  doubler: Number,
  flight: Number,
  green_armor: Number,
  guard: Number,
  haste: Number,
  health: Number,
  invis: Number,
  invulnerability: Number,
  kamikaze: Number,
  medkit: Number,
  mega_health: Number,
  other_holdable: Number,
  other_powerup: Number,
  portal: Number,
  quad: Number,
  red_armor: Number,
  regen: Number,
  scout: Number,
  teleporter: Number,
  yellow_armor: Number
};